### ISSUE TITLE
ArgumentCountError

### ISSUE THREAD

**Issue by mbsued** [b13/container#279]
With Typo3 10.4.31 and container 2.0.0the following error appears:
1/1) ArgumentCountError
Too few arguments to function B13\Container\Hooks\TableConfigurationPostProcessing::__construct(), 0 passed in /html/typo3/typo3_src-10.4.31/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3480 and exactly 1 expected

**Comment by nebrot** [comment]
Same problem for us:

container 2.0.0
TYPO3 11.5.12
PHP 7.4
Non-composer

**Comment by achimfritz** [comment]
@mbsued  do you also run Non-Composer-Mode?

**Comment by mbsued** [comment]
i run non_composer mode

**Comment by achimfritz** [comment]
@mbsued have you tried flushing caches and dump autoload in Install Tool?

**Comment by mbsued** [comment]
backend is not useable after updating to 2.0.0

**Comment by anderlk** [comment]
Same Problem here on TYPO3 11.5.13 non_composer.

**Comment by szerner** [comment]
I had this issue too and wasn't even able to get into the install tool. After clearing up the typo3temp folder backend and frontend is up and running again. Non composer mode.

**Comment by anderlk** [comment]
> After upgrading from v.1.6.1 to 2.0.0 I had this issue too and wasn't even able to get into the install tool. After clearing up the `/typo3temp` folder backend and frontend is up and running again. Non composer mode.

Thanks that solves the problem for me.

**Comment by mbsued** [comment]
clearing up the /typo3temp folder solved the problem.

**Comment by vmans** [comment]
Removing /typo3temp and clearing caches and all, does not help, the error remains:


(1/1) ArgumentCountError

Too few arguments to function B13\Container\Backend\Grid\ContainerGridColumn::__construct(), 3 passed in /var/www/clients/.../typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3208 and at least 4 expected

**Comment by asche76** [comment]
error still occours with container 2.0.2 (T3 11.5.15)

**Comment by achimfritz** [comment]
Hi (non-composer-) guys, anyone have still problems with DI (after flushing cache + dump autolaod + clear typo3temp?)? because this is not a general bug. Else i will close this issu

**Comment by mbsued** [comment]
No more Problems you can close.
